name: Deploy Micro-Frontend App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install & Build Host
        working-directory: host
        run: |
          npm install
          npm run build

      - name: Install & Build Map MFE
        working-directory: mapMFE
        run: |
          npm install
          npm run build

      - name: Install & Build Tools MFE
        working-directory: toolsMFE
        run: |
          npm install
          npm run build

      - name: Deploy Host to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: host/dist
          publish_branch: gh-pages
      # Add deployment steps (e.g., deploying to GitHub Pages, Vercel, etc.)
      # ...existing deployment steps...
